# Generated by Django 3.2.11 on 2022-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILine_app', '0002_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
